<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[On Suite Execution started]]>
    </line>
    <line>
      <![CDATA[Configure the Report]]>
    </line>
    <line>
      <![CDATA[Connected with the database]]>
    </line>
    <line>
      <![CDATA[Configure Parallel Exe]]>
    </line>
    <line>
      <![CDATA[Launch the browser]]>
    </line>
    <line>
      <![CDATA[Navigated and logged in]]>
    </line>
    <line>
      <![CDATA[On Test Execution started]]>
    </line>
    <line>
      <![CDATA[Test Execution Failed]]>
    </line>
    <line>
      <![CDATA[logout]]>
    </line>
    <line>
      <![CDATA[Close the browser]]>
    </line>
    <line>
      <![CDATA[Close the parallel Exe]]>
    </line>
    <line>
      <![CDATA[Disconnected with the Database]]>
    </line>
  </reporter-output>
  <suite started-at="2025-06-17T17:30:22 IST" name="Default suite" finished-at="2025-06-17T17:30:38 IST" duration-ms="16639">
    <groups>
    </groups>
    <test started-at="2025-06-17T17:30:22 IST" name="Default test" finished-at="2025-06-17T17:30:38 IST" duration-ms="16639">
      <class name="ContactModule.ContactScenariosTest">
        <test-method is-config="true" signature="connectionWithDB()[pri:0, instance:ContactModule.ContactScenariosTest@58a9760d]" started-at="2025-06-17T17:30:21 IST" name="connectionWithDB" finished-at="2025-06-17T17:30:22 IST" duration-ms="332" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Connected with the database]]>
            </line>
          </reporter-output>
        </test-method> <!-- connectionWithDB -->
        <test-method is-config="true" signature="configParallelExe()[pri:0, instance:ContactModule.ContactScenariosTest@58a9760d]" started-at="2025-06-17T17:30:22 IST" name="configParallelExe" finished-at="2025-06-17T17:30:22 IST" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Configure Parallel Exe]]>
            </line>
          </reporter-output>
        </test-method> <!-- configParallelExe -->
        <test-method is-config="true" signature="LaunchTheBrowser()[pri:0, instance:ContactModule.ContactScenariosTest@58a9760d]" started-at="2025-06-17T17:30:22 IST" name="LaunchTheBrowser" finished-at="2025-06-17T17:30:23 IST" duration-ms="1526" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Launch the browser]]>
            </line>
          </reporter-output>
        </test-method> <!-- LaunchTheBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:ContactModule.ContactScenariosTest@58a9760d]" started-at="2025-06-17T17:30:23 IST" name="login" finished-at="2025-06-17T17:30:28 IST" duration-ms="4813" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Navigated and logged in]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createContTest()[pri:0, instance:ContactModule.ContactScenariosTest@58a9760d]" started-at="2025-06-17T17:30:28 IST" name="createContTest" finished-at="2025-06-17T17:30:36 IST" duration-ms="7824" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at ContactModule.ContactScenariosTest.createContTest(ContactScenariosTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[On Test Execution started]]>
            </line>
            <line>
              <![CDATA[Test Execution Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- createContTest -->
        <test-method is-config="true" signature="logout()[pri:0, instance:ContactModule.ContactScenariosTest@58a9760d]" started-at="2025-06-17T17:30:36 IST" name="logout" finished-at="2025-06-17T17:30:38 IST" duration-ms="1997" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[logout]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="closeTheBrowser()[pri:0, instance:ContactModule.ContactScenariosTest@58a9760d]" started-at="2025-06-17T17:30:38 IST" name="closeTheBrowser" finished-at="2025-06-17T17:30:38 IST" duration-ms="291" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Close the browser]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeTheBrowser -->
        <test-method is-config="true" signature="closeParallelExe()[pri:0, instance:ContactModule.ContactScenariosTest@58a9760d]" started-at="2025-06-17T17:30:38 IST" name="closeParallelExe" finished-at="2025-06-17T17:30:38 IST" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Close the parallel Exe]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeParallelExe -->
        <test-method is-config="true" signature="closetheConnWithDB()[pri:0, instance:ContactModule.ContactScenariosTest@58a9760d]" started-at="2025-06-17T17:30:38 IST" name="closetheConnWithDB" finished-at="2025-06-17T17:30:38 IST" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Disconnected with the Database]]>
            </line>
          </reporter-output>
        </test-method> <!-- closetheConnWithDB -->
      </class> <!-- ContactModule.ContactScenariosTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
